name: Build and Push passwd Docker Image
description: This workflow builds and pushes the passwd Docker image to Docker Hub on every push to the main branch.

on:
  push:
    branches: ["main"]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            soyroberto/passwd:latest
            soyroberto/passwd:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max